<?php

// Collection import

$strings = array(
    "Collection import" => "Import sbírky",
    "Import" => "Import",
    "Yes" => "Ano",
    "No" => "Ne",
    "OK" => "OK",
    "Loading details..." => "Načítám podrobnosti...",
    "Unable to load import detail." => "Nepodařilo se načíst podrobnosti importu.",
    "%n (version %v)" => "%n (verze %v)",
    "Previous imports" => "Předchozí importy",
    "Name" => "Název",
    "Date" => "Datum",
    "Format" => "Formát",
    "Status" => "Stav",
    "New import" => "Nový import",
    "Select file to import:" => "Zvolte soubor, který chcete importovat:",
    "Imported file format:" => "Formát importovaného souboru:",
    "Import options" => "Nastavení importu",
    "Collection" => "Sbírka",
    "Collect new CWGs" => "Zařadit CWG, která doposud ve sbírce nemáte",
    "Remove from collection already collected CWGs" => "Vyřadit CWG, která máte ve sbírce",
    "Offers, wants, notwants" => "Nabízím, sháním, nechci",
    "Set new offers" => "Nastavit nové nabídky",
    "Unset existing offers" => "Odstranit existující nabídky",
    "Exclusive mode" => "Výhradní mód",
    "Import!" => "Importovat!",
    "Choose file to import from your local device and format of the imported file." =>
        "Zvolte soubor, který chcete importovat z vašeho zařízení a formát importovaného souboru.",
    "Also, pay attention to import options to choose what exactly you want to import." =>
        "Pomocí nastavení importu si můžete zvolit, co přesně chcete ze souboru importovat.",
    "Following table summarizes what actions the import will do." =>
        "Následující tabulka shrnuje, které akce budou během importu provedeny.",
    "Action" => "Akce",
    "Will be performed?" => "Bude provedena?",
    "Collect new CWGs that you currently don't have in your collection, but are in the imported file." =>
        "Zařadit nová CWG, která ještě nemáte ve sbírce, ale jsou v importovaném souboru.",
    "Remove from collection CWGs that are specified in the import file as you don't own." =>
        "Odstranit ze sbírky CWG, která jsou uvedena v importovaném souboru jako že je nemáte.",
    "Remove from collection CWGs that are not present in the import file." =>
        "Odstranit z kolekce CWG, která se nevyskytují v importovaném souboru.",
    "Set new offers flags (offers, wants, don't want) as specified in the import file." =>
        "Přidat příznaky nabízím, sháním, nechci podle toho, jak jsou uvedeny v importovaném souboru",
    "Unset existing offer flags (offers, wants, don't want) to match ones in the import file." =>
        "Odstranit existující příznaky nabízím, sháním, nechci podle toho, jak jsou uvedeny v importovaném souboru.",
    "Unset existing offer flags for CWGs that are not present in the imported file." =>
        "Odstranit existující příznaky nabízím, sháním, nechci u těch CWG, která nejsou uvedena v importovaném souboru.",
    "Back" => "Zpět",
    "Summary" => "Souhrn",
    "Import name:" => "Název importu:",
    "Date created:" => "Datum vytvoření:",
    "Date finished:" => "Datum dokončení:",
    "Total CWGs:" => "Celkem CWG:",
    "Collected:" => "Zařazeno:",
    "Uncollected:" => "Vyřazeno:",
    "Modified:" => "Změněno:",
    "Unmodified:" => "Nezměněno:",
    "Errors:" => "Chyby:",
    "Detail" => "Podrobnosti",
    "Modified" => "Změneno",
    "Not modified" => "Nezměněno",
    "Unable to uniquely identify the CWG." => "Nepodařilo se unikátně identifikovat CWG.",
    "CWG does not exists." => "CWG neexistuje.",
    "Error while processing the CWG" => "Při zpracovávání CWG došlo k chybě.",
    "Removed from collection." => "Vyřazeno ze sbírky",
    "Import file is not a valid XML file." => "Importovaný soubor není validním XML.",
    "Import file is not valid against XML schema." => "Importovaný soubor není validní podle XML schématu.",
    "You must select import file." => "Musíte vybrat soubor pro import.",
    "You must specify valid import format." => "Musíte vybrat formát importovaného souboru.",
    "File upload failed." => "Nahrávání souboru selhalo.",
    "Import has been created and placed into queue for processing." => "Import byl vytvořen a zařazen do fronty ke zpracování.",
    "Import was not found" => "Import nebyl nalezen.",
    "New" => "Nový",
    "Waiting" => "Čeká na zpracování",
    "Processing" => "Zpracovává se",
    "Done" => "Hotovo",
    "Error" => "Selhalo",
    "Invalid input file" => "Chybný vstupní soubor",
    "Warning! Exclusive mode will overwrite your entire collection based on flags specified above. Use with caution!" => "Varování! Výhradní mód přepíše celou vaši sbírku podle toho, co se nachází v importovaném souboru. Používejte tuto volbu s opatrností!",
);
