<?php

// Collection import

$strings = array(
    "Collection import" => "Import kolekcji",
    "Import" => "Import",
    "Yes" => "Tak",
    "No" => "Nie",
    "OK" => "OK",
    "Loading details..." => "Wczytuję szczegóły...",
    "Unable to load import detail." => "Nie udało się wczytać danych importu.",
    "%n (version %v)" => "%n (wersja %v)",
    "Previous imports" => "Poprzednie importy",
    "Name" => "Nazwa",
    "Date" => "Data",
    "Format" => "Format",
    "Status" => "Status",
    "New import" => "Nowy import",
    "Select file to import:" => "Wybierz plik do zaimportowania:",
    "Imported file format:" => "Format importowanego pliku:",
    "Import options" => "Opcje importu",
    "Collection" => "Kolekcja",
    "Collect new CWGs" => "Zbierz nowe xWG",
    "Remove from collection already collected CWGs" => "Usuń z kolekcji już posiadanie xWG",
    "Offers, wants, notwants" => "Oferowane, chciane, niechciane",
    "Set new offers" => "Ustaw nową ofertę",
    "Unset existing offers" => "Odznacz istniejącą ofertę",
    "Exclusive mode" => "Tryb Exclusive",
    "Import!" => "Importuj!",
    "Choose file to import from your local device and format of the imported file." =>
        "Wybierz plik do importu z dysku i format importowanego pliku.",
    "Also, pay attention to import options to choose what exactly you want to import." =>
        "Pamiętaj także o opcjach importu, aby wybrać dokładnie importowane obiekty.",
    "Following table summarizes what actions the import will do." =>
        "Tabela podsumowuje akcje, których dokona import.",
    "Action" => "Akcja",
    "Will be performed?" => "Do przetworzenia?",
    "Collect new CWGs that you currently don't have in your collection, but are in the imported file." =>
        "Zbierz nowe xWG, których obecnie nie posiadasz w kolekcji, ale znajdują się w pliku.",
    "Remove from collection CWGs that are specified in the import file as you don't own." =>
        "Usuń z kolekcji xWG, które są w pliku oznaczone jako nieposiadane.",
    "Remove from collection CWGs that are not present in the import file." =>
        "Usuń z kolekcji xWG, które nie istnieją w pliku.",
    "Set new offers flags (offers, wants, don't want) as specified in the import file." =>
        "Ustaw flagi ofert zgodnie z plikiem.",
    "Unset existing offer flags (offers, wants, don't want) to match ones in the import file." =>
        "Zmień istniejące flagi ofert tak, by zgadzały się z plikiem.",
    "Unset existing offer flags for CWGs that are not present in the imported file." =>
        "Odznacz flagi ofert, które nie istnieją w importowanym pliku.",
    "Back" => "Wstecz",
    "Summary" => "Podsumowanie",
    "Import name:" => "Nazwa importu:",
    "Date created:" => "Data utworzenia:",
    "Date finished:" => "Data ukończenia:",
    "Total CWGs:" => "Wszystkich xWG:",
    "Collected:" => "Zebrane:",
    "Uncollected:" => "Nie zebrane:",
    "Modified:" => "Zmodyfikowane:",
    "Unmodified:" => "Niemodyfikowane:",
    "Errors:" => "Błędy:",
    "Detail" => "Szczegóły",
    "Modified" => "Zmodyfikowane",
    "Not modified" => "Niemodyfikowane",
    "Unable to uniquely identify the CWG." => "Nie udało się wskazać odpowiedniego xWG.",
    "CWG does not exists." => "xWG nie istnieje.",
    "Error while processing the CWG" => "Błąd w procesowaniu xWG.",
    "Removed from collection." => "Usunięto z kolekcji",
    "Import file is not a valid XML file." => "Importowany plik jest niepoprawnym plikiem XML.",
    "Import file is not valid against XML schema." => "Importowany plik nie jest zgodny ze schematem XML.",
    "You must select import file." => "Wybierz plik do importu.",
    "You must specify valid import format." => "Wybierz poprawny format pliku.",
    "File upload failed." => "Błąd przesyłu pliku.",
    "Import has been created and placed into queue for processing." => "Import utworzono i umieszczono w kolejce do procesowania.",
    "Import was not found" => "Nie znaleziono importu.",
    "New" => "Nowy",
    "Waiting" => "W oczekiwaniu",
    "Processing" => "Procesowany",
    "Done" => "Gotowy",
    "Error" => "Błąd",
    "Invalid input file" => "Zły plik wejściowy",
    "Warning! Exclusive mode will overwrite your entire collection based on flags specified above. Use with caution!" => "UWAGA! Tryb Exclusive nadpisze twoją całą kolekcję zgodnie z flagami powyżej. Używać z ostrożnością!",
);
