<?php
// Collection import
$strings = array(
    "Collection import" => "Import zbierky",
    "Import" => "Import",
    "Yes" => "Áno",
    "No" => "Nie",
    "OK" => "OK",
    "Loading details..." => "Načítajú sa podrobnosti...",
    "Unable to load import detail." => "Nepodarilo sa načítať podrobnosti importu.",
    "%n (version %v)" => "%n (verzia %v)",
    "Previous imports" => "Predchádzajúce importy",
    "Name" => "Názov",
    "Date" => "Dátum",
    "Format" => "Formát",
    "Status" => "Stav",
    "New import" => "Nový import",
    "Select file to import:" => "Vyberte súbor, ktorý chcete importovať:",
    "Imported file format:" => "Formát importovaného súboru:",
    "Import options" => "Nastavenie importu",
    "Collection" => "Zbierka",
    "Collect new CWGs" => "Zaradiť xWG, ktoré dosiaľ v zbierke nemáte",
    "Remove from collection already collected CWGs" => "Vyradiť xWG, ktoré máte v zbierke",
    "Offers, wants, notwants" => "Ponúkam zháňam, nechcem",
    "Set new offers" => "Nastaviť nové ponuky",
    "Unset existing offers" => "Odstrániť existujúce ponuky",
    "Exclusive mode" => "Výhradný režim",
    "Import!" => "Importovať!",
    "Choose file to import from your local device and format of the imported file." =>
        "Vyberte súbor, ktorý chcete importovať z vášho zariadenia a formát importovaného súboru.",
    "Also, pay attention to import options to choose what exactly you want to import." =>
        "Pomocou nastavenia importu môžete vybrať, čo presne chcete zo súboru importovať.",
    "Following table summarizes what actions the import will do." =>
        "Nasledujúca tabuľka obsahuje zhrnutie, ktoré úkony budú počas importu vykonané.",
    "Action" => "Úkon",
    "Will be performed?" => "Bude vykonaný?",
    "Collect new CWGs that you currently don't have in your collection, but are in the imported file." =>
        "Zaradiť nové xWG, ktoré ešte nemáte v zbierke, ale sú v importovanom súbore.",
    "Remove from collection CWGs that are specified in the import file as you don't own." =>
        "Odstrániť zo zbierky xWG, ktoré sú uvedené v importovanom súbore ako také, ktoré nemáte.",
    "Remove from collection CWGs that are not present in the import file." =>
        "Odstrániť zo zbierky xWG, ktoré sa nevyskytujú v importovanom súbore.",
    "Set new offers flags (offers, wants, don't want) as specified in the import file." =>
        "Pridať príznaky (ponúkam, zháňam, nechcem) podľa toho, ako sú uvedené v importovanom súbore.",
    "Unset existing offer flags (offers, wants, don't want) to match ones in the import file." =>
        "Odstrániť existujúce príznaky (ponúkam, zháňam, nechcem) podľa toho, ako sú uvedené v importovanom súbore.",
    "Unset existing offer flags for CWGs that are not present in the imported file." =>
        "Odstrániť existujúce príznaky (ponúkam, zháňam, nechcem) pri tých xWG, ktoré nie sú uvedené v importovanom súbore.",
    "Back" => "Späť",
    "Summary" => "Súhrn",
    "Import name:" => "Názov importu:",
    "Date created:" => "Dátum vytvorenia:",
    "Date finished:" => "Dátum dokončenia:",
    "Total CWGs:" => "Celkom xWG:",
    "Collected:" => "Zaradené:",
    "Uncollected:" => "Vyradené:",
    "Modified:" => "Zmenené:",
    "Unmodified:" => "Nezmenené:",
    "Errors:" => "Chyby:",
    "Detail" => "Podrobnosti",
    "Modified" => "Zmenené",
    "Not modified" => "Nezmenené",
    "Unable to uniquely identify the CWG." => "Nepodarilo sa unikátne identifikovať xWG.",
    "CWG does not exists." => "xWG neexistuje.",
    "Error while processing the CWG" => "Pri spracovaní xWG sa vyskytla chyba.",
    "Removed from collection." => "Vyradené zo zbierky",
    "Import file is not a valid XML file." => "Importovaný súbor nie je platné XML.",
    "Import file is not valid against XML schema." => "Importovaný súbor nie je platný podľa schémy XML.",
    "You must select import file." => "Musíte vybrať súbor na import.",
    "You must specify valid import format." => "Musíte vybrať formát importovaného súboru.",
    "File upload failed." => "Nahrávanie súboru neúspešné.",
    "Import has been created and placed into queue for processing." => "Import bol vytvorený a zaradený do frontu na spracovanie.",
    "Import was not found" => "Import sa nenašiel.",
    "New" => "Nový",
    "Waiting" => "Čaká na spracovanie",
    "Processing" => "Spracováva sa",
    "Done" => "Hotovo",
    "Error" => "Neúspešné",
    "Invalid input file" => "Chybný vstupný súbor",
    "Warning! Exclusive mode will overwrite your entire collection based on flags specified above. Use with caution!" => "Varovanie! Výhradný režim prepíše celú vašu zbierku podľa toho, čo sa nachádza v importovanom súbore. Používajte túto možnosť opatrne!",
);
